spring:
  profiles:
    # 默认使用开发环境 dev 开发 test 演示 prod 生产
    active: dev

# pagehelper分页插件
pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true

mybatis:
  # mapper.xml包地址
  mapper-locations: classpath:mapper/*.xml
  # pojo生成包地址
  type-aliases-package: com.yang.demo.springboot.mybatis.po

#应用配置
resources:
  # log文件写入地址
  logdir: logs/
  # 应用名称
  appname: spring-boot
  # 日志打印的基础扫描包
  basepackage: com.yang.demo.springboot